# Generated by Django 4.2.4 on 2023-10-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('assunto', models.CharField(max_length=50)),
                ('assunto_email', models.CharField(max_length=1000)),
            ],
        ),
    ]
