# Generated by Django 4.2.4 on 2023-10-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='assunto_email',
            field=models.TextField(max_length=1000),
        ),
    ]
