# Generated by Django 4.2.4 on 2023-10-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_contato_assunto_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
